config/routes.rb
Rails.application.routes.draw do
  resources :orders
  authenticate :user, lambda { |u| u.user_role == "admin" } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
  get 'contact/index'
  get 'about/index'
  resources :line_items
  resources :carts
  resources :products
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'homepage/index'
  root "homepage#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cart
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'THANK YOU FOR BUYING WITH US.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:province, :district, :phonenumber, :pay_method, :accept, :user_id, :cart_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Plant Nursery Managment System</title>
<link rel="shortcut icon" href="assets/favicon.png" type="image/png">
<!-- custom-theme -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Germinate Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //custom-theme -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="assets/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- js -->
<script type="text/javascript" src="assets/jquery-2.1.4.min.js"></script>
<!-- //js -->
<link href="assets/mislider.css" rel="stylesheet" type="text/css" />
<link href="assets/mislider-custom.css" rel="stylesheet" type="text/css" />
<!-- font-awesome-icons -->
<link href="assets/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome-icons -->
<link href="//fonts.googleapis.com/css?family=Bree+Serif&amp;subset=latin-ext" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="w3_agile_logo">
			<h1><a href="localhost:3000"><span>P</span> NM system<i>Plant Nursery Management System</i></a></h1>
		</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20rem;">
        <li class="nav-item">
          <%= link_to "Home", root_url, class:"nav-link",style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "All product", products_path, class:"nav-link", style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_index_path, class:"nav-link", style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", contact_index_path, class:"nav-link", style:"color:#fff;" %>
        </li>
      </ul>
    </div>
</nav><br><br>
<div class="container" style="font-size:15px;">
<center>
      <div class="row">
        <table class="table table-bordered">
        <thead class="bg-dark">
          <tr>
            <th scope="col" style="color:white;">Image</th>
            <th scope="col" style="color:white;">Name</th>
            <th scope="col" style="color:white;">Details</th>
            <th scope="col" style="color:white;">Price</th>
            <th scope="col" style="color:white;">Quantity</th>
            <th scope="col" style="color:white;">SubTotal</th>
          </tr>
        </thead>
        <%= render(@cart.line_items) %>
        <tr>
            <td colspan="5"></td>
            <td id="cat" style="color:black;">Total Price:<%= number_to_currency(@cart.total_price, :unit => "RWF") %></td>
        </tr>
        </table>
      </div>
    </center>
  <%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
      <div class="col-md-6">
        <% if user_signed_in? %>
          <div class="card">
            <div class="card-header bg-dark" style="color:#fff;">
                Personal Information
            </div>
            <div class="card-body">
              <strong>FullName</strong><p class="card-text"><%= current_user.fullname %></p>
              <strong>Email</strong><p class="card-text"><%= current_user.email %></p>
              <strong>PhoneNumber</strong><p class="card-text"><%= current_user.phonenumber %></p>
              <strong>Address</strong><p class="card-text"><%= current_user.address %></p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
          <div class="card">
            <div class="card-header bg-dark" style="color:#fff;">
                Shipping Address
            </div>
            <div class="card-body">
              <p class="card-text"><strong>Enter Province</strong>:
                <%= form.text_field :province, class:"form-control", placeholder:"Enter Shipping Province", required:"required" %></p>
              <p class="card-text"><strong>Enter District</strong>:
                <%= form.text_field :district, class:"form-control", placeholder:"Enter Shipping District", required:"required" %></p>
              <p class="card-text"><strong>Enter PhoneNumber</strong>:
                <%= form.text_field :phonenumber, class:"form-control", placeholder:"Enter Phone Number", required:"required" %></p>
            </div>
          </div>
      </div>
    </div><br>
      <div class="container" style="background:#343a40">
      <div class="row">
        <div class="col-md-12">
          <%= form.radio_button :pay_method, 'Contact Seller Before Pay' %> <strong style="font-size: 18px;color:#a4dd25">Contact Seller Before Pay</strong>: <selif style="color:#fff;">Our Sales Team Will Contact You In order To Proced Your Order With 1Hour In Working hours</selif><br />
          <%= form.radio_button :pay_method, 'Pay With Momo' %> <strong style="font-size: 18px;color:#a4dd25"> Pay With Momo</strong>: <selif style="color:#fff;">Pay With Our MoMo Code And Contact Our Sales Team Inorder To Ship Your Package<br /></selif>
          <%= form.radio_button :pay_method, 'Pay With Card' %> <strong style="font-size: 18px;color:#a4dd25"> Pay With Card </strong>: <selif style="color:#fff;">Under Constration<br /></selif>
        </div>
      </div>
      </div><br>
      <div class="row">
        <div class="col-md-12">
          <%= form.check_box :accept, class:"largerCheckbox" %><strong style="font-size: 25px;"> Accept</strong>
        </div>
      </div><br>
      <div class="row">
        <div class="col-md-12">
          <%= form.hidden_field :user_id, value: current_user.id %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= form.hidden_field :cart_id, :value => params[:cart_id] if params[:cart_id]%>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= form.submit 'Order Now', class:"w3ls_more", style:"padding:15px;font-size:15px;border-radius:10px;width:150px;" %>
        </div>
      </div>
    </div><br><br><br>
<% end %>
</body>
</html>

app/views/orders/edit.html.erb
<%= render 'form', order: @order %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Province</th>
      <th>District</th>
      <th>Phonenumber</th>
      <th>Pay method</th>
      <th>Accept</th>
      <th>User</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.province %></td>
        <td><%= order.district %></td>
        <td><%= order.phonenumber %></td>
        <td><%= order.pay_method %></td>
        <td><%= order.accept %></td>
        <td><%= order.user %></td>
        <td><%= order.cart %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Province:</strong>
  <%= @order.province %>
</p>

<p>
  <strong>District:</strong>
  <%= @order.district %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @order.phonenumber %>
</p>

<p>
  <strong>Pay method:</strong>
  <%= @order.pay_method %>
</p>

<p>
  <strong>Accept:</strong>
  <%= @order.accept %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @order.cart %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>