config/routes.rb
Rails.application.routes.draw do
  resources :orders
  authenticate :user, lambda { |u| u.user_role == "admin" } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
  get 'contact/index'
  get 'about/index'
  resources :line_items
  resources :carts
  resources :products
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'homepage/index'
  root "homepage#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  mount_uploader :product_image, ImageUploader
  has_many :line_items

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:product_image, :image_cache)
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:product_name, :product_image, :product_details, :sales_price, :regular_price, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Plant Nursery Managment System</title>
<link rel="shortcut icon" href="assets/favicon.png" type="image/png">
<!-- custom-theme -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Germinate Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //custom-theme -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="assets/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- js -->
<script type="text/javascript" src="assets/jquery-2.1.4.min.js"></script>
<!-- //js -->
<link href="assets/mislider.css" rel="stylesheet" type="text/css" />
<link href="assets/mislider-custom.css" rel="stylesheet" type="text/css" />
<!-- font-awesome-icons -->
<link href="assets/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome-icons -->
<link href="//fonts.googleapis.com/css?family=Bree+Serif&amp;subset=latin-ext" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="w3_agile_logo">
			<h1><a href="localhost:3000"><span>P</span> NM system<i>Plant Nursery Management System</i></a></h1>
		</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20rem;">
        <li class="nav-item">
          <%= link_to "Home", root_url, class:"nav-link",style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "All product", products_path, class:"nav-link", style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_index_path, class:"nav-link", style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", contact_index_path, class:"nav-link", style:"color:#fff;" %>
        </li>
      </ul>
    </div>
</nav>
<h3 class="agileits_w3layouts_head">Add <span>Product</span></h3>
<div class="container" style="margin-left:15rem;">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= form.label :product_name %>
      <%= form.text_field :product_name, class:"form-control", placeholder:"Enter Product Name" %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :product_image, class:"input-group-text", for:"inputGroupFile01" %>
      <%= form.file_field :product_image, class:"form-control", id:"inputGroupFile01" %>
    </div>
  </div>
  <div class="form-group" style="width:46rem;">
    <%= form.label :product_details %>
      <%= form.text_area :product_details, class:"form-control", placeholder:"Enter Product Details" %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= form.label :sales_price %>
      <%= form.text_field :sales_price, class:"form-control", placeholder:"Enter Sales Price" %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :regular_price %>
      <%= form.text_field :regular_price, class:"form-control", placeholder:"Enter Regular Price" %>
    </div>
  </div>
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <%= form.submit "Add Product", class:"w3ls_more" %>
<% end %>
</div>
</body><br><br><br><br><br><br>
</html>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Plant Nursery Managment System</title>
<link rel="shortcut icon" href="assets/favicon.png" type="image/png">
<!-- custom-theme -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Germinate Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //custom-theme -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="assets/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- js -->
<script type="text/javascript" src="assets/jquery-2.1.4.min.js"></script>
<!-- //js -->
<link href="assets/mislider.css" rel="stylesheet" type="text/css" />
<link href="assets/mislider-custom.css" rel="stylesheet" type="text/css" />
<!-- font-awesome-icons -->
<link href="assets/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome-icons -->
<link href="//fonts.googleapis.com/css?family=Bree+Serif&amp;subset=latin-ext" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="w3_agile_logo">
			<h1><a href="localhost:3000"><span>P</span> NM system<i>Plant Nursery Management System</i></a></h1>
		</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20rem;">
        <li class="nav-item">
          <%= link_to "Home", root_url, class:"nav-link",style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "All product", products_path, class:"nav-link", style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_index_path, class:"nav-link", style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", contact_index_path, class:"nav-link", style:"color:#fff;" %>
        </li>
      </ul>
    </div>
</nav>
  <div class="container" id="ourproduct">
			<h3 class="agileits_w3layouts_head">All <span>Product</span></h3>
			<div class="w3_agile_image">
				<img src="assets/1.png" alt=" " class="img-responsive">
			</div>
			<div class="w3ls_news_grids">
				<% @products.each do |product| %>
				<div class="col-md-4 w3ls_news_grid">
					<div class="w3layouts_news_grid">
						<%= link_to product do %>
						    <%= image_tag product.product_image.url, class:"img-responsive" %>
						<% end %>
						<div class="w3layouts_news_grid_pos">
							<div class="wthree_text">
								<h3>
									<%= product.product_name %><br>
									<%= number_to_currency(product.sales_price, :unit => "RWF") %>
								</h3>
							</div>
						</div>
					</div>
					<div class="agileits_w3layouts_news_grid">
						<ul>
							<li id="regular">
								<% if product.regular_price.present? %>
								  <%= number_to_currency(product.regular_price, :unit => "RWF") %>
								<% end %>
							</li>
							<li>
							    <%= number_to_currency(product.sales_price, :unit => "RWF") %>
							</li>
						</ul>
						<ul>
							<li>
								<%= link_to product, class:"w3l_contact" do %>
								  <i class="fa fa-shopping-cart", style="color:black;"></i>Add to cart
								<% end %>
							</li>
							<li>
								<%= link_to product, class:"w3ls_more" do %>
								  <i class="fa fa-link", style="color:black;"></i>View Details
								<% end %>
							</li>
						</ul>
						<h4>
							<%= link_to product do %>
								<%= product.product_name %>
							<% end %>
						</h4>
						<p></p>
					</div><br><br>
				</div>
				<% end %>
				<div class="clearfix"> </div>
			</div>
		</div>
</body>
</html>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Plant Nursery Managment System</title>
<link rel="shortcut icon" href="assets/favicon.png" type="image/png">
<!-- custom-theme -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Germinate Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //custom-theme -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="assets/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- js -->
<script type="text/javascript" src="assets/jquery-2.1.4.min.js"></script>
<!-- //js -->
<link href="assets/mislider.css" rel="stylesheet" type="text/css" />
<link href="assets/mislider-custom.css" rel="stylesheet" type="text/css" />
<!-- font-awesome-icons -->
<link href="assets/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome-icons -->
<link href="//fonts.googleapis.com/css?family=Bree+Serif&amp;subset=latin-ext" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="w3_agile_logo">
			<h1><a href="localhost:3000"><span>P</span> NM system<i>Plant Nursery Management System</i></a></h1>
		</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left:20rem;">
        <li class="nav-item">
          <%= link_to "Home", root_url, class:"nav-link",style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "All product", products_path, class:"nav-link", style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_index_path, class:"nav-link", style:"color:#fff;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", contact_index_path, class:"nav-link", style:"color:#fff;" %>
        </li>
      </ul>
    </div>
</nav><br><br><br>
<div class="container">
    <div class="row">
        <div class="col-md-4 shadow p-3 mb-5 bg-white rounded productshow">
          <div class="image-gallery">
            <div id="big">
              <%= image_tag @product.product_image.url %>
            </div>  
          </div> 
        </div>
    <div class="col-md-6 shadow p-3 mb-5 bg-white rounded">
      <h1 style="color:#46a9fa;font-size: 30px;">
        <%= @product.product_name %>
      </h1>
      <h6 class="card-text" style="font-size: 15px;">
        <strong id="category">Product Description:</strong> <%= @product.product_details.truncate(50) %>
      </h6>
      <h5 class="card-text" style="font-size: 15px;">
        <strong id="category">Price:</strong><%= number_to_currency(@product.sales_price, :unit => "RWF") %>
      </h5>
      <h6 id="regular" style="font-size: 15px;">
        <% if @product.regular_price.present? %>
          <%= number_to_currency(@product.regular_price, :unit => "RWF") %>
        <% end %>
      </h6>
      <div class="col-md-12">
        <div class="col-md-4">
          <%= button_to 'Add to cart', line_items_path(product_id: @product), class:"w3ls_more", style:'padding:15px;font-size:15px;border-radius:10px;width:150px;' %>
        </div>
        <div class="col-md-4">
          <%= button_to 'Pay Now', line_items_path(product_id: @product), class:"w3l_contact", style:'padding:15px;font-size:15px;border-radius:10px;width:150px;' %>
      </div>
      </div>
    </div>
  </div>
  </div>
</body><br><br><br><br><br><br>
</html>